name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .chart-testing.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config .chart-testing.yaml

      - name: Set up podman
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          source /etc/os-release
          echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
          curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Set up oc client
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          wget https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          sudo tar xzvf oc.tar.gz -C /usr/local/bin

      - name: Run a microshift cluster
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          sudo podman run -d --rm --name microshift \
               --privileged -v microshift-data:/var/lib -p 6443:6443 \
               quay.io/microshift/microshift-aio:latest
          # get kubeconfig
          sudo podman exec microshift bash -c \
               'while ! test -f "/var/lib/microshift/resources/kubeadmin/kubeconfig";
               do
                   echo "Waiting for kubeconfig..."
                   sleep 5
               done'
          mkdir ${HOME}/.kube
          sudo podman cp \
               microshift:/var/lib/microshift/resources/kubeadmin/kubeconfig \
               ${HOME}/.kube/config
          sudo chown ${USER} ${HOME}/.kube/config
          chmod 600 ${HOME}/.kube/config
          # wait for the cluster to become available
          sleep 10
          kubectl wait --for=condition=available apiservice --all --timeout 300s

      - name: Install prometheus
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install --create-namespace --namespace metrics \
               prometheus-stack prometheus-community/kube-prometheus-stack

      - name: Install Tekton with the tekton operator
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl create ns openshift-operators
          kubectl apply -f https://storage.googleapis.com/tekton-releases/operator/latest/openshift-release.yaml
          # to install pipelines and triggers only (use profile 'basic')
          kubectl apply -f https://raw.githubusercontent.com/tektoncd/operator/main/config/crs/openshift/config/basic/operator_v1alpha1_config_cr.yaml

      - name: Wait for the prerequisites to be ready
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          # workaround the lack of automatic CA cert info from cluster network operator
          while : ; do
              kubectl get namespace openshift-pipelines && sleep 5 && break
              sleep 5
          done
          kubectl create configmap config-trusted-cabundle \
              --from-file=ca-bundle.crt=/etc/ssl/certs/ca-certificates.crt \
              --dry-run=client -o yaml | \
              kubectl apply -n openshift-pipelines -f -
          # wait for Tekton to be ready
          kubectl wait tektonconfig config --for condition=ComponentsReady \
                   --timeout 600s

      - name: Run chart-testing (install)
        run: ct install --config .chart-testing.yaml
